### ISSUE TITLE
EI: unemployment rate types 

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#62] opened 2014-03-12 23:38 UTC
Consider a numeric unemployment rate as well as a percentage one.

**Comment by ElisaKendall** [comment] 2020-01-09 02:04
This issue was addressed with the refactoring of the definition of unemployment rate by the IND FCT.  The current definition reflects not only the rate value as published by the US, but for Canada and those countries that use the OECD specification for submitting their information to the IMF.

This was made moot by the work done by the IND FCT and should be re-closed.

**Comment by rivettp** [comment] 2020-01-09 02:47
I did look into this and could not see how to represent the absolute number e.g.  on 31 December 2019 the US had 2.5 million unemployed people.

**Comment by ElisaKendall** [comment] 2020-01-09 03:21
It's never an absolute number, it's an estimate.   I will spend some time creating individuals so that you can see how to do this - we spent months working on the model so that it worked.  This issue, which is about having subclasses, is not the same as being able to represent instances as published on the BLS site, for example, at https://www.bls.gov/news.release/empsit.a.htm.

We have been working on other use cases recently, but I would be delighted to work with you on a use case that Dan can assist with and demonstrate how to represent the published numbers.  But I will need help representing all of the various aspects / characteristics and ways to slice and dice the nunbers they publish to get it right.  We paused on that because MA wanted to work on market rates.  We could go back to it, but I'd like to actually finish one use case before working on a different one.  But this issue is not the right place to work on that.  This issue should be closed and in the context of the use case, open other issues as needed, or not.

**Comment by trypuz** [comment] 2020-01-18 22:00
I agree with @ElisaKendall. Let's close this issue and define a new one clearly defining the problem.

**Closed by trypuz** 2020-01-18 22:00 UTC
Labels: IND

**Comment by rivettp** [comment] 2020-01-19 00:22
It's untrue to say unemployment is only quoted in percentages. For example from https://tradingeconomics.com/united-states/unemployment-rate "The US unemployment rate held steady at 3.5 percent in December 2019, remaining at the lowest level since 1969 and in line with market expectations. The number of unemployed people decreased by 58 thousand to 5.75 million while employment rose by 267 thousand to 158.80 million. "
The problem is clear - that the ontology does not allow you represent the 5.75 million. If you want me to jump through hoops and open a new issue rather than working on a solution so be it, but it won't say much different.
